# Generated by Django 3.2.7 on 2021-10-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.TextField()),
                ('image', models.ImageField(upload_to='album/')),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
