# Generated by Django 3.2.7 on 2021-11-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasimit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='github_url',
            field=models.URLField(blank=True),
        ),
    ]
