# Generated by Django 3.2.7 on 2021-11-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasimit', '0002_expert_github_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('short_description', models.TextField()),
                ('image', models.ImageField(upload_to='project/')),
            ],
        ),
    ]
