# Generated by Django 3.2.7 on 2021-11-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasimit', '0004_project_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('short_description', models.TextField()),
                ('image', models.ImageField(upload_to='testimonials/')),
            ],
        ),
    ]
