# Generated by Django 3.2.7 on 2021-11-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasimit', '0005_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short_description', models.TextField()),
                ('image', models.ImageField(upload_to='service/')),
            ],
        ),
    ]
