# Generated by Django 3.2.7 on 2021-11-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasimit', '0006_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partner/')),
                ('hover_image', models.ImageField(upload_to='partner/')),
            ],
        ),
    ]
