# Generated by Django 3.2.7 on 2021-11-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasimit', '0008_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
    ]
