# Generated by Django 3.2.7 on 2021-11-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasimit', '0009_appoinment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appoinment',
            new_name='Appointment',
        ),
    ]
