# Generated by Django 3.2.7 on 2021-11-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasimit', '0011_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
