# Generated by Django 3.2.7 on 2021-11-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasimit', '0012_auto_20211117_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='blog/')),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
