# Generated by Django 3.2.7 on 2021-11-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasimit', '0014_auto_20211119_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/'),
        ),
    ]
